### get one text
GET {{url}}
Accept: application/json

### get all texts
GET {{url}}?all=yes
Accept: application/json

### create text
POST {{url}}
Accept: application/json
Content-Type: application/json

{
  "text": "     welcome, bienvenido, bienvenue, willkommen, benvenuto, bem-vindo, welkom, dobro pozhalovat', huan ying, karibu, hwangyonghamnida, kalos orisate, valkommen, barukh haba, witajcie, selamat datang   "
}

