### get text
GET {{url}}
Accept: application/json


### create text
POST {{url}}
Accept: application/json
Content-Type: application/json

{
  "text": "     valeria, porque tienes siempre que leer todo?"
}